import os
import json

# ── Default configurations (seeded on first run) ─────────────────────────────

DEFAULTS = [
    # ── General ──────────────────────────────────────────────────────────────
    {
        "key": "general.system_name",
        "value": "OpenW Security",
        "value_type": "string",
        "category": "general",
        "label": "Nombre del sistema",
        "description": "Nombre del sistema que aparece en la interfaz y comunicaciones.",
        "is_sensitive": False,
    },
    {
        "key": "general.organization_name",
        "value": "Fiduprevisora",
        "value_type": "string",
        "category": "general",
        "label": "Nombre de la organización",
        "description": "Nombre de la organización mostrado en reportes y correos.",
        "is_sensitive": False,
    },
    {
        "key": "general.session_timeout_minutes",
        "value": "3",
        "value_type": "number",
        "category": "general",
        "label": "Timeout de sesión (minutos)",
        "description": "Tiempo máximo de inactividad antes de expirar una conversación de WhatsApp.",
        "is_sensitive": False,
    },
    {
        "key": "general.frontend_url",
        "value": os.getenv("FRONTEND_URL", "http://localhost:1111"),
        "value_type": "string",
        "category": "general",
        "label": "URL del frontend",
        "description": "URL base del dashboard (usada en links de correos de verificación).",
        "is_sensitive": False,
    },

    # ── WhatsApp ──────────────────────────────────────────────────────────────
    {
        "key": "whatsapp.access_token",
        "value": os.getenv("WHATSAPP_ACCESS_TOKEN", ""),
        "value_type": "string",
        "category": "whatsapp",
        "label": "Access Token",
        "description": "Token de acceso a la API de WhatsApp Cloud de Meta (se renueva cada 24h en entornos de prueba).",
        "is_sensitive": True,
    },
    {
        "key": "whatsapp.phone_number_id",
        "value": os.getenv("WHATSAPP_PHONE_NUMBER_ID", ""),
        "value_type": "string",
        "category": "whatsapp",
        "label": "Phone Number ID",
        "description": "ID del número de teléfono registrado en Meta Business.",
        "is_sensitive": False,
    },
    {
        "key": "whatsapp.business_account_id",
        "value": os.getenv("WHATSAPP_BUSINESS_ACCOUNT_ID", ""),
        "value_type": "string",
        "category": "whatsapp",
        "label": "Business Account ID",
        "description": "ID de la cuenta de negocio en Meta.",
        "is_sensitive": False,
    },
    {
        "key": "whatsapp.app_id",
        "value": os.getenv("WHATSAPP_APP_ID", ""),
        "value_type": "string",
        "category": "whatsapp",
        "label": "App ID",
        "description": "ID de la aplicación de Meta.",
        "is_sensitive": False,
    },
    {
        "key": "whatsapp.verify_token",
        "value": os.getenv("WHATSAPP_VERIFY_TOKEN", ""),
        "value_type": "string",
        "category": "whatsapp",
        "label": "Verify Token (Webhook)",
        "description": "Token de verificación del webhook configurado en Meta.",
        "is_sensitive": True,
    },
    {
        "key": "whatsapp.app_secret",
        "value": os.getenv("WHATSAPP_APP_SECRET", ""),
        "value_type": "string",
        "category": "whatsapp",
        "label": "App Secret",
        "description": "Secreto de la app de Meta, usado para validar firmas HMAC de los webhooks.",
        "is_sensitive": True,
    },

    # ── Email ─────────────────────────────────────────────────────────────────
    {
        "key": "email.gmail_user",
        "value": os.getenv("GMAIL_USER", ""),
        "value_type": "string",
        "category": "email",
        "label": "Usuario Gmail (SMTP)",
        "description": "Dirección de correo de Gmail usada para enviar verificaciones.",
        "is_sensitive": False,
    },
    {
        "key": "email.gmail_app_password",
        "value": os.getenv("GMAIL_APP_PASSWORD", ""),
        "value_type": "string",
        "category": "email",
        "label": "Contraseña de aplicación Gmail",
        "description": "Contraseña de aplicación generada en la cuenta de Google (no es la contraseña normal).",
        "is_sensitive": True,
    },
    {
        "key": "email.allowed_domain",
        "value": os.getenv("ALLOWED_EMAIL_DOMAIN", ""),
        "value_type": "string",
        "category": "email",
        "label": "Dominio de email corporativo",
        "description": "Solo se aceptarán correos de este dominio (ej: fiduprevisora.com).",
        "is_sensitive": False,
    },

    # ── Analysis ──────────────────────────────────────────────────────────────
    {
        "key": "analysis.auto_classify",
        "value": "true",
        "value_type": "boolean",
        "category": "analysis",
        "label": "Clasificación automática",
        "description": "Cuando está activo, el sistema clasifica automáticamente la categoría de cada novedad usando palabras clave.",
        "is_sensitive": False,
    },
    {
        "key": "analysis.ai_validation",
        "value": "true",
        "value_type": "boolean",
        "category": "analysis",
        "label": "Validación con IA",
        "description": "Usa IA (Deepseek) como fallback para validar entradas del usuario en el chat de WhatsApp.",
        "is_sensitive": False,
    },
    {
        "key": "analysis.critical_keywords",
        "value": json.dumps(["ransomware", "cifrado", "exfiltración", "backdoor", "zero-day", "brecha", "compromiso"]),
        "value_type": "json",
        "category": "analysis",
        "label": "Palabras clave de criticidad",
        "description": "Lista de términos que elevan automáticamente una novedad a severidad CRÍTICA.",
        "is_sensitive": False,
    },
    {
        "key": "analysis.high_keywords",
        "value": json.dumps(["phishing", "malware", "intrusión", "acceso no autorizado", "escalada de privilegios"]),
        "value_type": "json",
        "category": "analysis",
        "label": "Palabras clave de severidad Alta",
        "description": "Lista de términos que clasifican una novedad como severidad ALTA.",
        "is_sensitive": False,
    },

    # ── Modules ───────────────────────────────────────────────────────────────
    {
        "key": "modules.bot_enabled",
        "value": "true",
        "value_type": "boolean",
        "category": "modules",
        "label": "Bot de WhatsApp",
        "description": "Activa o desactiva globalmente el bot de WhatsApp. Cuando está desactivado, los mensajes entrantes son ignorados.",
        "is_sensitive": False,
    },
    {
        "key": "modules.email_notifications",
        "value": "true",
        "value_type": "boolean",
        "category": "modules",
        "label": "Notificaciones por correo",
        "description": "Activa o desactiva el envío de correos de verificación de email.",
        "is_sensitive": False,
    },
    {
        "key": "modules.embeddings",
        "value": "true",
        "value_type": "boolean",
        "category": "modules",
        "label": "Embeddings semánticos",
        "description": "Activa la generación de embeddings vectoriales para búsqueda semántica en conversaciones.",
        "is_sensitive": False,
    },

    # ── External APIs ─────────────────────────────────────────────────────────
    {
        "key": "external.virustotal_enabled",
        "value": "false",
        "value_type": "boolean",
        "category": "external_apis",
        "label": "VirusTotal habilitado",
        "description": "Activa el análisis automático de archivos/URLs adjuntas a novedades usando VirusTotal.",
        "is_sensitive": False,
    },
    {
        "key": "external.virustotal_api_key",
        "value": "",
        "value_type": "string",
        "category": "external_apis",
        "label": "API Key de VirusTotal",
        "description": "Clave de API de VirusTotal para escaneo de indicadores.",
        "is_sensitive": True,
    },
    {
        "key": "external.deepseek_api_key",
        "value": os.getenv("DEEPSEEK_API_KEY", ""),
        "value_type": "string",
        "category": "external_apis",
        "label": "API Key de Deepseek",
        "description": "Clave de API de Deepseek utilizada para validación inteligente de entradas.",
        "is_sensitive": True,
    },
]
