import type { VulnerabilityCase, Category, DashboardMetrics, BotMetrics } from "./types"

export const mockCases: VulnerabilityCase[] = [
  {
    id: "VULN-001",
    title: "SQL Injection en formulario de login",
    description: "Se detectó vulnerabilidad de inyección SQL en el endpoint /api/v1/auth/login",
    severity: "critical",
    status: "open",
    reportedBy: "Juan García",
    reportedAt: new Date("2026-03-15T10:30:00"),
    category: "Inyección",
    keywords: ["sql", "injection", "auth"],
    whatsappNumber: "+52 555 123 4567",
    lastUpdated: new Date("2026-03-15T10:30:00"),
  },
  {
    id: "VULN-002",
    title: "XSS Reflejado en búsqueda",
    description: "Posible XSS en el campo de búsqueda principal sin sanitización",
    severity: "high",
    status: "in_progress",
    reportedBy: "María López",
    reportedAt: new Date("2026-03-14T14:20:00"),
    assignedTo: "Carlos Ramírez",
    category: "Cross-Site Scripting",
    keywords: ["xss", "reflected", "search"],
    whatsappNumber: "+52 555 987 6543",
    lastUpdated: new Date("2026-03-15T09:00:00"),
  },
  {
    id: "VULN-003",
    title: "Exposición de API Keys",
    description: "API keys expuestas en el código fuente del frontend",
    severity: "critical",
    status: "resolved",
    reportedBy: "Pedro Sánchez",
    reportedAt: new Date("2026-03-13T08:45:00"),
    assignedTo: "Ana Torres",
    category: "Exposición de Datos",
    keywords: ["api", "keys", "exposure"],
    whatsappNumber: "+52 555 456 7890",
    lastUpdated: new Date("2026-03-14T16:30:00"),
  },
  {
    id: "VULN-004",
    title: "CSRF en cambio de contraseña",
    description: "Falta de token CSRF en el formulario de cambio de contraseña",
    severity: "medium",
    status: "open",
    reportedBy: "Laura Mendoza",
    reportedAt: new Date("2026-03-12T11:15:00"),
    category: "Cross-Site Request Forgery",
    keywords: ["csrf", "password", "token"],
    whatsappNumber: "+52 555 321 0987",
    lastUpdated: new Date("2026-03-12T11:15:00"),
  },
  {
    id: "VULN-005",
    title: "Acceso no autorizado a endpoints",
    description: "Falta de verificación de roles en endpoints administrativos",
    severity: "high",
    status: "in_progress",
    reportedBy: "Roberto Díaz",
    reportedAt: new Date("2026-03-11T16:00:00"),
    assignedTo: "Carlos Ramírez",
    category: "Control de Acceso",
    keywords: ["authorization", "roles", "admin"],
    whatsappNumber: "+52 555 654 3210",
    lastUpdated: new Date("2026-03-13T10:00:00"),
  },
  {
    id: "VULN-006",
    title: "Certificado SSL expirado",
    description: "Certificado SSL del subdominio api.example.com expirado",
    severity: "low",
    status: "closed",
    reportedBy: "Sistema Automático",
    reportedAt: new Date("2026-03-10T09:30:00"),
    assignedTo: "Infraestructura",
    category: "Configuración",
    keywords: ["ssl", "certificate", "expired"],
    whatsappNumber: "+52 555 111 2222",
    lastUpdated: new Date("2026-03-10T12:00:00"),
  },
  {
    id: "VULN-007",
    title: "Fuga de información en headers",
    description: "Headers de respuesta revelan versiones de servidor y framework",
    severity: "low",
    status: "open",
    reportedBy: "Miguel Ángel",
    reportedAt: new Date("2026-03-09T13:45:00"),
    category: "Exposición de Datos",
    keywords: ["headers", "information", "disclosure"],
    whatsappNumber: "+52 555 333 4444",
    lastUpdated: new Date("2026-03-09T13:45:00"),
  },
  {
    id: "VULN-008",
    title: "Buffer Overflow en upload",
    description: "Posible buffer overflow al subir archivos grandes sin límite",
    severity: "medium",
    status: "resolved",
    reportedBy: "Sandra Vega",
    reportedAt: new Date("2026-03-08T15:20:00"),
    assignedTo: "Ana Torres",
    category: "Overflow",
    keywords: ["buffer", "upload", "file"],
    whatsappNumber: "+52 555 555 6666",
    lastUpdated: new Date("2026-03-09T18:00:00"),
  },
]

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Inyección",
    description: "Vulnerabilidades de inyección de código (SQL, NoSQL, OS, LDAP)",
    keywords: ["sql", "injection", "nosql", "ldap", "os command"],
    createdAt: new Date("2026-01-01"),
    color: "#ef4444",
  },
  {
    id: "cat-2",
    name: "Cross-Site Scripting",
    description: "Ataques XSS reflejados, almacenados y basados en DOM",
    keywords: ["xss", "reflected", "stored", "dom", "script"],
    createdAt: new Date("2026-01-01"),
    color: "#f97316",
  },
  {
    id: "cat-3",
    name: "Exposición de Datos",
    description: "Fugas de información sensible o datos expuestos",
    keywords: ["data", "exposure", "leak", "sensitive", "pii"],
    createdAt: new Date("2026-01-01"),
    color: "#eab308",
  },
  {
    id: "cat-4",
    name: "Control de Acceso",
    description: "Problemas de autenticación y autorización",
    keywords: ["auth", "authorization", "access", "roles", "permissions"],
    createdAt: new Date("2026-01-01"),
    color: "#22c55e",
  },
  {
    id: "cat-5",
    name: "Cross-Site Request Forgery",
    description: "Ataques CSRF y problemas de tokens",
    keywords: ["csrf", "token", "forgery", "request"],
    createdAt: new Date("2026-01-01"),
    color: "#3b82f6",
  },
  {
    id: "cat-6",
    name: "Configuración",
    description: "Errores de configuración de seguridad",
    keywords: ["config", "misconfiguration", "ssl", "tls", "headers"],
    createdAt: new Date("2026-01-01"),
    color: "#8b5cf6",
  },
  {
    id: "cat-7",
    name: "Overflow",
    description: "Buffer overflow y vulnerabilidades de memoria",
    keywords: ["buffer", "overflow", "memory", "heap", "stack"],
    createdAt: new Date("2026-01-01"),
    color: "#ec4899",
  },
]

export const mockMetrics: DashboardMetrics = {
  totalCases: 156,
  openCases: 42,
  resolvedToday: 8,
  avgResolutionTime: 4.2,
  bySeverity: {
    critical: 12,
    high: 28,
    medium: 45,
    low: 71,
  },
  byStatus: {
    open: 42,
    in_progress: 23,
    resolved: 67,
    closed: 24,
  },
  recentTrend: [
    { date: "Mar 13", count: 12 },
    { date: "Mar 14", count: 18 },
    { date: "Mar 15", count: 8 },
    { date: "Mar 16", count: 24 },
    { date: "Mar 17", count: 15 },
    { date: "Mar 18", count: 20 },
    { date: "Mar 19", count: 14 },
  ],
}

export const mockBotMetrics: BotMetrics = {
  totalConversations: 12,
  conversationsTrend: 100,
  responseRate: 75,
  responseTrend: 75,
  satisfactionRate: 0,
  satisfactionRatings: 1,
  usageOverTime: [
    { date: "2026-03-12", count: 0 },
    { date: "2026-03-13", count: 2 },
    { date: "2026-03-14", count: 5 },
    { date: "2026-03-15", count: 3 },
    { date: "2026-03-16", count: 8 },
    { date: "2026-03-17", count: 12 },
    { date: "2026-03-18", count: 12 },
  ],
  effectiveness: {
    conContexto: 75,
    sinContexto: 25,
  }
}
